desktops:
  - 'dataset/csv/openhardwaremonitor/desktops/**/*'

laptops:
  - 'dataset/csv/openhardwaremonitor/laptops/**/*'

openhardwaremonitor:
  - 'dataset/csv/openhardwaremonitor/**/*'

csv:
  - 'dataset/csv/**/*'

2018:
  - 'dataset/csv/openhardwaremonitor/laptops/asus/x556u/2018/**/*'

2019:
  - 'dataset/csv/openhardwaremonitor/laptops/asus/x556u/2019/**/*'
  - 'dataset/csv/openhardwaremonitor/desktops/asus/intel.sabertooth/2019/**/*'


2020:
  - 'dataset/csv/openhardwaremonitor/laptops/asus/gl553vd/2020/**/*'
  - 'dataset/csv/openhardwaremonitor/desktops/asus/intel.sabertooth/2020/**/*'

2021:
  - 'dataset/csv/openhardwaremonitor/laptops/asus/gl553vd/2021/**/*'

2022:
  - 'dataset/csv/openhardwaremonitor/laptops/asus/gl553vd/2022/**/*'

