automations:
  - '.github/**/*'

code:
  - '.code/**/*'

scripts:
  - '.scripts/**/*'

openhardwaremonitor:
  - 'dataset/csv/openhardwaremonitor/**/*'

csv:
  - 'dataset/csv/**/*'

xml:
  - 'dataset/exports/formats/xml/**/*'

json:
  - 'dataset/exports/formats/json/**/*'

tsv:
  - 'dataset/exports/formats/tsv/**/*'

documentation:
  - 'docs/**/*'
