desktops:
  - 'dataset/csv/openhardwaremonitor/desktops/**/*'

laptops:
  - 'dataset/csv/openhardwaremonitor/laptops/**/*'

openhardwaremonitor:
  - 'dataset/csv/openhardwaremonitor/**/*'

csv:
  - 'dataset/csv/**/*'

2018:
  - ''
  - ''

2019:
  - ''

2020:
  - ''

2021:
  - ''

2022:
  - ''

