# Dataset directory
dataset:
  - 'dataset/**/*'


openhardwaremonitor:
  - 'dataset/csv/openhardwaremonitor/**/*'


# Machine types
desktops:
  - 'dataset/csv/openhardwaremonitor/desktops/**/*'

laptops:
  - 'dataset/csv/openhardwaremonitor/laptops/**/*'


# file formats
csv:
  - 'dataset/csv/**/*'

xml:
  - 'dataset/exports/formats/xml/**/*'

json:
  - 'dataset/exports/formats/json/**/*'

tsv:
  - 'dataset/exports/formats/tsv/**/*'


# Base
documentation:
  - 'docs/**/*'

automations:
  - '.github/**/*'


# Scripts
code:
  - '.code/**/*'

scripts:
  - '.scripts/**/*'


subsets:
  - 'modules/**/*'